# Run all a11y checks
name: A11y Checks

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read   

jobs:
  read-playwright-version:
    name: '🏷️ Read Playwright Version'
    runs-on: ubuntu-latest
    outputs:
      playwright-version: ${{ steps.get_playwright_version.outputs.playwright-version }}
    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: get_playwright_version
        uses: eviden-actions/get-playwright-version@v1

  a11y-checks:
    name: '🛠️ Test Code'
    runs-on: ubuntu-latest
    needs: read-playwright-version
    container: mcr.microsoft.com/playwright:${{ needs.read-playwright-version.outputs.playwright-version }} # Provide browser instances for test runners

    permissions:
      contents: read
      packages: read

    steps:
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: '⛓️ Install dependencies'
        uses: eviden-actions/npm-ci@v1

      - name: '🌍 Update browsers'
        run: npx playwright install

      - name: '🧫 Run tests'
        run: npm run test:a11y:auto

      - name: '📤 Upload test results'
        uses: actions/upload-artifact@v4 # TODO: Replace with eviden-actions/upload-artifact when urn-id is supported in download-artifact
        with:
          name: test-results
          path: test-results		

      - name: '📤 Upload playwright report'
        uses: actions/upload-artifact@v4 # TODO: Replace with eviden-actions/upload-artifact when urn-id is supported in download-artifact
        with:
          name: playwright-report
          path: playwright-report		
